site_name: Hello
site_author: wk-j

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - csharp
